In [2]:
import torch

print(torch.__version__)

2.14.0+cu130


In [3]:
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)   #scaler 0-dimension
print(scalar.shape)       
print(scalar.dtype)

0
torch.Size([])
torch.int64


In [5]:
vector = torch.tensor([7, 7])

print(vector)
print(vector.ndim)      #vector 1-dimension
print(vector.shape)
print(vector.dtype)

tensor([7, 7])
1
torch.Size([2])
torch.int64


In [6]:
matrix = torch.tensor([
    [7, 8],
    [9, 10]
])

print(matrix.ndim)   #matrix 2-dimension
print(matrix.shape)     
print(matrix.dtype)

2
torch.Size([2, 2])
torch.int64


In [7]:
print(matrix[0, 0])
print(matrix[0, 1])       # matrix -indexing
print(matrix[1, 0])
print(matrix[1, 1])

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [8]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],                 # 3-dimensional tensor
        [10, 11, 12]
    ]
])

print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [9]:
print(tensor_3d[0, 0, 0])
print(tensor_3d[0, 1, 2]) #indexing
print(tensor_3d[1, 0, 2])
print(tensor_3d[1, 1, 1])

tensor(1)
tensor(6)
tensor(9)
tensor(11)


In [10]:
print(tensor_3d[1])
print(tensor_3d[1][0])
print(tensor_3d[1][0][2])

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([7, 8, 9])
tensor(9)


In [11]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print(float_tensor)
print(float_tensor.dtype)
print(float_tensor.shape)
print(float_tensor.ndim)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
1


In [12]:
float_64_tensor = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=torch.float64
)

print(float_64_tensor)
print(float_64_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


In [13]:
vector_float = vector.to(dtype=torch.float32)

print(vector)
print(vector.dtype)

print(vector_float)
print(vector_float.dtype)

tensor([7, 7])
torch.int64
tensor([7., 7.])
torch.float32


In [14]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [15]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

elementwise_result = tensor_a * tensor_b       # element-wise multiplication


print(elementwise_result)

tensor([ 4, 10, 18])


In [18]:
matrix_result = torch.matmul(tensor_a, tensor_b)  # matrix-multiplication

print(matrix_result)

tensor(32)


In [20]:
matrix_a = torch.tensor([
    [1, 2],
    [3, 4]
])
                 # matrix multiplication with 2D matrices
                        
matrix_b = torch.tensor([
    [5, 6],
    [7, 8]
])

result = torch.matmul(matrix_a, matrix_b)

print(result)

tensor([[19, 22],
        [43, 50]])


In [21]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a.shape)
print(b.shape)

result = torch.matmul(a, b)

print(result)
print(result.shape)

torch.Size([2, 3])
torch.Size([3, 4])
tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128]])
torch.Size([2, 4])
