In [3]:
import torch

print(torch.__version__)

2.14.0+cpu


In [4]:
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [5]:
print(scalar.ndim)   #scaler 0-dimension
print(scalar.shape)       
print(scalar.dtype)

0
torch.Size([])
torch.int64


In [6]:
vector = torch.tensor([7, 7])

print(vector)
print(vector.ndim)      #vector 1-dimension
print(vector.shape)
print(vector.dtype)

tensor([7, 7])
1
torch.Size([2])
torch.int64


In [7]:
matrix = torch.tensor([
    [7, 8],
    [9, 10]
])

print(matrix.ndim)   #matrix 2-dimension
print(matrix.shape)     
print(matrix.dtype)

2
torch.Size([2, 2])
torch.int64


In [8]:
print(matrix[0, 0])
print(matrix[0, 1])       # matrix -indexing
print(matrix[1, 0])
print(matrix[1, 1])

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [9]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],                 # 3-dimensional tensor
        [10, 11, 12]
    ]
])

print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [10]:
print(tensor_3d[0, 0, 0])
print(tensor_3d[0, 1, 2]) #indexing
print(tensor_3d[1, 0, 2])
print(tensor_3d[1, 1, 1])

tensor(1)
tensor(6)
tensor(9)
tensor(11)


In [11]:
print(tensor_3d[1])
print(tensor_3d[1][0])
print(tensor_3d[1][0][2])

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([7, 8, 9])
tensor(9)


In [12]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print(float_tensor)
print(float_tensor.dtype)
print(float_tensor.shape)
print(float_tensor.ndim)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
1


In [13]:
float_64_tensor = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=torch.float64
)

print(float_64_tensor)
print(float_64_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


In [14]:
vector_float = vector.to(dtype=torch.float32)

print(vector)
print(vector.dtype)

print(vector_float)
print(vector_float.dtype)

tensor([7, 7])
torch.int64
tensor([7., 7.])
torch.float32


In [15]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [16]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

elementwise_result = tensor_a * tensor_b       # element-wise multiplication


print(elementwise_result)

tensor([ 4, 10, 18])


In [17]:
matrix_result = torch.matmul(tensor_a, tensor_b)  # matrix-multiplication

print(matrix_result)

tensor(32)


In [18]:
matrix_a = torch.tensor([
    [1, 2],
    [3, 4]
])
                 # matrix multiplication with 2D matrices
                        
matrix_b = torch.tensor([
    [5, 6],
    [7, 8]
])

result = torch.matmul(matrix_a, matrix_b)

print(result)

tensor([[19, 22],
        [43, 50]])


In [19]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a.shape)
print(b.shape)

result = torch.matmul(a, b)

print(result)
print(result.shape)

torch.Size([2, 3])
torch.Size([3, 4])
tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128]])
torch.Size([2, 4])


In [20]:
print(a)

print(a.T)

print(a.shape)
print(a.T.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])


In [21]:
inputs = torch.tensor([2.0, 3.0, 4.0])

weights = torch.tensor([0.5, 0.2, 0.1])

bias = torch.tensor(0.5)

output = torch.matmul(inputs, weights) + bias

print(output)

tensor(2.5000)


In [22]:
import torch.nn as nn #import neural network

In [23]:
linear_layer = nn.Linear(
    in_features=3,
    out_features=1
)

print(linear_layer)

Linear(in_features=3, out_features=1, bias=True)


In [24]:
print(linear_layer.weight)
print(linear_layer.bias)

print(linear_layer.weight.shape)
print(linear_layer.bias.shape)

Parameter containing:
tensor([[-0.4123,  0.1130, -0.3355]], requires_grad=True)
Parameter containing:
tensor([0.4295], requires_grad=True)
torch.Size([1, 3])
torch.Size([1])


In [25]:
inputs = torch.tensor([2.0, 3.0, 4.0])

output = linear_layer(inputs)

print(output)

tensor([-1.3983], grad_fn=<ViewBackward0>)


In [26]:
print(output.requires_grad)
print(output.grad_fn)

True


In [27]:
print(inputs.requires_grad)
print(linear_layer.weight.requires_grad)
print(linear_layer.bias.requires_grad)
print(output.requires_grad)
print(output.grad_fn)

False
True
True
True


In [28]:
x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [29]:
y.backward()

print(x.grad)

tensor(6.)


In [30]:
x1 = 3.0
x2 = 3.001

y1 = x1 ** 2
y2 = x2 ** 2

change_in_x = x2 - x1
change_in_y = y2 - y1

estimated_gradient = change_in_y / change_in_x

print(change_in_x)
print(change_in_y)
print(estimated_gradient)

0.0009999999999998899
0.006000999999999479
6.00100000000014


In [31]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)


In [32]:
loss.backward()

print(weight.grad)

tensor(-32.)


In [33]:
learning_rate = 0.1

with torch.no_grad():
    weight -= learning_rate * weight.grad
    
print("Updated weight:", weight)

Updated weight: tensor(4.2000, requires_grad=True)


In [34]:
prediction = weight * input_value 

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(8.4000, grad_fn=<MulBackward0>)
Loss: tensor(2.5600, grad_fn=<PowBackward0>)


In [35]:
weight.grad.zero_()

 # reset gradient

print(weight.grad)

tensor(0.)


In [36]:
loss.backward()

print(weight.grad)

tensor(-6.4000)


In [37]:
with torch.no_grad():
    weight -= learning_rate * weight.grad # update new weight = old weight−(learning rate×gradient)


print("Updated weight:", weight)

Updated weight: tensor(4.8400, requires_grad=True)


In [38]:
prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(9.6800, grad_fn=<MulBackward0>)
Loss: tensor(0.1024, grad_fn=<PowBackward0>)


In [39]:
for epoch in range(5):
    print("Epoch", epoch + 1) # 1-5
    

Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


In [40]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

for epoch in range(5):
    prediction = weight * input_value

    loss =  (prediction - target) ** 2

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction)
    print("Loss:", loss)

Epoch: 1
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 2
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 3
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 4
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 5
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)


In [41]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

prediction = weight * input_value

loss =  (prediction - target) ** 2

loss.backward()

print("Prediction", prediction)
print("Loss", loss)
print("Gradient", weight.grad)

Prediction tensor(2., grad_fn=<MulBackward0>)
Loss tensor(64., grad_fn=<PowBackward0>)
Gradient tensor(-32.)


In [42]:
weight.grad.zero_()

print("Gradient after reset:", weight.grad)

Gradient after reset: tensor(0.)


In [43]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

learning_rate = 0.1

for epoch in range(5):

    prediction = weight * input_value      #1×2=2

    loss = (prediction - target) ** 2      # (2 - 10) raise to power 2

    loss.backward() # backpropagation

    with torch.no_grad():
        weight -= learning_rate * weight.grad   # weight=1−(0.1×−32)

    weight.grad.zero_()

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction.item())
    print("Loss:", loss.item())
    print("Weight:", weight.item())
    print()

Epoch: 1
Prediction: 2.0
Loss: 64.0
Weight: 4.199999809265137

Epoch: 2
Prediction: 8.399999618530273
Loss: 2.5600011348724365
Weight: 4.840000152587891

Epoch: 3
Prediction: 9.680000305175781
Loss: 0.1023998036980629
Weight: 4.9679999351501465

Epoch: 4
Prediction: 9.935999870300293
Loss: 0.004096016753464937
Weight: 4.993599891662598

Epoch: 5
Prediction: 9.987199783325195
Loss: 0.00016384554328396916
Weight: 4.998720169067383



In [44]:
weight = torch.tensor(1.0, requires_grad=True)

optimizer = torch.optim.SGD(
    [weight],
    lr=0.1
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [45]:
input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

prediction = weight * input_value
loss = (prediction - target) ** 2

loss.backward()

print("Weight before optimizer:", weight.item())
print("Gradient:", weight.grad.item())

Weight before optimizer: 1.0
Gradient: -32.0


In [46]:
optimizer.step()

print("Weight after optimizer:", weight.item())

Weight after optimizer: 4.199999809265137


In [47]:
print("Gradient before zero_grad:", weight.grad)

optimizer.zero_grad()

print("Gradient after zero_grad:", weight.grad)

Gradient before zero_grad: tensor(-32.)
Gradient after zero_grad: None


In [48]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

optimizer = torch.optim.SGD([weight], lr=0.1)

for epoch in range(5):

    optimizer.zero_grad()

    prediction = weight * input_value

    loss = (prediction - target) ** 2

    loss.backward()

    optimizer.step()

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction.item())
    print("Loss:", loss.item())
    print("Weight:", weight.item())
    print()

Epoch: 1
Prediction: 2.0
Loss: 64.0
Weight: 4.199999809265137

Epoch: 2
Prediction: 8.399999618530273
Loss: 2.5600011348724365
Weight: 4.840000152587891

Epoch: 3
Prediction: 9.680000305175781
Loss: 0.1023998036980629
Weight: 4.9679999351501465

Epoch: 4
Prediction: 9.935999870300293
Loss: 0.004096016753464937
Weight: 4.993599891662598

Epoch: 5
Prediction: 9.987199783325195
Loss: 0.00016384554328396916
Weight: 4.998720169067383



In [49]:
linear_model = nn.Linear(
    in_features=1,
    out_features=1
)

print(linear_model)

print("Weight:", linear_model.weight)
print("Bias:", linear_model.bias)

print("Weight shape:", linear_model.weight.shape)
print("Bias shape:", linear_model.bias.shape)

Linear(in_features=1, out_features=1, bias=True)
Weight: Parameter containing:
tensor([[0.8889]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.5228], requires_grad=True)
Weight shape: torch.Size([1, 1])
Bias shape: torch.Size([1])


In [50]:
input_value = torch.tensor([[2.0]])

prediction = linear_model(input_value)

print("Input shape:", input_value.shape)
print("Prediction:", prediction)
print("Prediction shape:", prediction.shape)

Input shape: torch.Size([1, 1])
Prediction: tensor([[1.2549]], grad_fn=<AddmmBackward0>)
Prediction shape: torch.Size([1, 1])


In [51]:
target = torch.tensor([[10.0]])

loss = (prediction - target) ** 2

print("Prediction", prediction)
print("Loss", loss)
print("Target", target)

Prediction tensor([[1.2549]], grad_fn=<AddmmBackward0>)
Loss tensor([[76.4765]], grad_fn=<PowBackward0>)
Target tensor([[10.]])


In [52]:
loss.backward()

print("Weight gradient:", linear_model.weight.grad)
print("Bias gradient:", linear_model.bias.grad)

Weight gradient: tensor([[-34.9803]])
Bias gradient: tensor([-17.4902])


In [53]:
optimizer = torch.optim.SGD(
    linear_model.parameters(),
    lr=0.01
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [54]:
optimizer.step()

print("Updated weight:", linear_model.weight)
print("Updated bias:", linear_model.bias)

Updated weight: Parameter containing:
tensor([[1.2387]], requires_grad=True)
Updated bias: Parameter containing:
tensor([-0.3479], requires_grad=True)


In [55]:
new_prediction = linear_model(input_value)
new_loss = (new_prediction - target) ** 2

print("Old prediction:", prediction)
print("New prediction:", new_prediction)
print("Old loss:", loss)
print("New loss:", new_loss)

Old prediction: tensor([[1.2549]], grad_fn=<AddmmBackward0>)
New prediction: tensor([[2.1294]], grad_fn=<AddmmBackward0>)
Old loss: tensor([[76.4765]], grad_fn=<PowBackward0>)
New loss: tensor([[61.9460]], grad_fn=<PowBackward0>)


In [56]:
print("Weight gradient still stored:", linear_model.weight.grad)
print("Bias gradient still stored:", linear_model.bias.grad)

Weight gradient still stored: tensor([[-34.9803]])
Bias gradient still stored: tensor([-17.4902])


In [57]:
optimizer.zero_grad()

print("Weight gradient after zero_grad:", linear_model.weight.grad)
print("Bias gradient after zero_grad:", linear_model.bias.grad)

Weight gradient after zero_grad: None
Bias gradient after zero_grad: None


In [58]:
new_loss.backward()

print("New weight gradient:", linear_model.weight.grad)
print("New bias gradient:", linear_model.bias.grad)

New weight gradient: tensor([[-31.4823]])
New bias gradient: tensor([-15.7412])


In [59]:
optimizer.step()

print("Updated weight:", linear_model.weight)
print("Updated bias:", linear_model.bias)

Updated weight: Parameter containing:
tensor([[1.5535]], requires_grad=True)
Updated bias: Parameter containing:
tensor([-0.1905], requires_grad=True)


In [60]:
print("Current weight:", linear_model.weight)
print("Current bias:", linear_model.bias)

print("Current weight gradient:", linear_model.weight.grad)
print("Current bias gradient:", linear_model.bias.grad)

print("Learning rate:", optimizer.param_groups[0]["lr"])

Current weight: Parameter containing:
tensor([[1.5535]], requires_grad=True)
Current bias: Parameter containing:
tensor([-0.1905], requires_grad=True)
Current weight gradient: tensor([[-31.4823]])
Current bias gradient: tensor([-15.7412])
Learning rate: 0.01


In [61]:
torch.manual_seed(42)

linear_model = nn.Linear(
    in_features=1,
    out_features=1
)

print("Starting weight:", linear_model.weight)
print("Starting bias:", linear_model.bias)

Starting weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Starting bias: Parameter containing:
tensor([0.8300], requires_grad=True)


In [62]:
input_value = torch.tensor([[2.0]])
target = torch.tensor([[10.0]])

optimizer = torch.optim.SGD(
    linear_model.parameters(),
    lr=0.01
)

prediction = linear_model(input_value)
loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)

Prediction: tensor([[2.3591]], grad_fn=<AddmmBackward0>)
Loss: tensor([[58.3836]], grad_fn=<PowBackward0>)


In [63]:
for epoch in range(10):

    optimizer.zero_grad()

    prediction = linear_model(input_value)

    loss = (prediction - target) ** 2

    loss.backward()

    optimizer.step()

    print(
        "Epoch:", epoch + 1,
        "| Prediction:", prediction.item(),
        "| Loss:", loss.item(),
        "| Weight:", linear_model.weight.item(),
        "| Bias:", linear_model.bias.item()
    )

Epoch: 1 | Prediction: 2.3590850830078125 | Loss: 58.38357925415039 | Weight: 1.0701751708984375 | Bias: 0.9828262329101562
Epoch: 2 | Prediction: 3.1231765747070312 | Loss: 47.29069900512695 | Weight: 1.3452481031417847 | Bias: 1.1203627586364746
Epoch: 3 | Prediction: 3.810858964920044 | Loss: 38.30546951293945 | Weight: 1.5928137302398682 | Bias: 1.2441456317901611
Epoch: 4 | Prediction: 4.429773330688477 | Loss: 31.02742576599121 | Weight: 1.8156228065490723 | Bias: 1.3555501699447632
Epoch: 5 | Prediction: 4.986795902252197 | Loss: 25.13221549987793 | Weight: 2.016150951385498 | Bias: 1.455814242362976
Epoch: 6 | Prediction: 5.488116264343262 | Loss: 20.35709571838379 | Weight: 2.1966261863708496 | Bias: 1.5460518598556519
Epoch: 7 | Prediction: 5.939304351806641 | Loss: 16.489248275756836 | Weight: 2.3590540885925293 | Bias: 1.6272658109664917
Epoch: 8 | Prediction: 6.34537410736084 | Loss: 13.356290817260742 | Weight: 2.5052390098571777 | Bias: 1.700358271598816
Epoch: 9 | Predi

In [64]:
inputs = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])

targets = torch.tensor([
    [5.0],
    [10.0],
    [15.0],
    [20.0]
])

print("Inputs:")
print(inputs)

print("Input shape:", inputs.shape)

print("\nTargets:")
print(targets)

print("Target shape:", targets.shape)

Inputs:
tensor([[1.],
        [2.],
        [3.],
        [4.]])
Input shape: torch.Size([4, 1])

Targets:
tensor([[ 5.],
        [10.],
        [15.],
        [20.]])
Target shape: torch.Size([4, 1])


In [65]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

predictions = multi_model(inputs)

print("Starting weight:", multi_model.weight)
print("Starting bias:", multi_model.bias)

print("\nPredictions:")
print(predictions)

print("\nPrediction shape:", predictions.shape)

Starting weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Starting bias: Parameter containing:
tensor([0.8300], requires_grad=True)

Predictions:
tensor([[1.5945],
        [2.3591],
        [3.1236],
        [3.8882]], grad_fn=<AddmmBackward0>)

Prediction shape: torch.Size([4, 1])


In [66]:
squared_errors = (predictions - targets) ** 2   # calculating losses

print("Squared errors:")
print(squared_errors)

print("Squared errors shape:", squared_errors.shape)

Squared errors:
tensor([[ 11.5971],
        [ 58.3836],
        [141.0483],
        [259.5913]], grad_fn=<PowBackward0>)
Squared errors shape: torch.Size([4, 1])


In [67]:
loss = squared_errors.mean()  # loss average sum of value by numbers of value

print("Mean squared error:", loss)
print("Loss shape:", loss.shape)
print("Loss dimensions:", loss.ndim)

Mean squared error: tensor(117.6551, grad_fn=<MeanBackward0>)
Loss shape: torch.Size([])
Loss dimensions: 0


In [68]:
mse_loss = nn.MSELoss()

loss_from_pytorch = mse_loss(predictions, targets)

print("Manual MSE:", loss)
print("PyTorch MSE:", loss_from_pytorch)

Manual MSE: tensor(117.6551, grad_fn=<MeanBackward0>)
PyTorch MSE: tensor(117.6551, grad_fn=<MseLossBackward0>)


In [69]:
print("Weight gradient before backward:", multi_model.weight.grad)
print("Bias gradient before backward:", multi_model.bias.grad)

Weight gradient before backward: None
Bias gradient before backward: None


In [70]:
loss_from_pytorch.backward() # propagation

print("Weight gradient:", multi_model.weight.grad)
print("Bias gradient:", multi_model.bias.grad)

Weight gradient: tensor([[-59.3819]])
Bias gradient: tensor([-19.5173])


In [71]:
optimizer.step()

print("Updated weight:", multi_model.weight)
print("Updated bias:", multi_model.bias)

Updated weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Updated bias: Parameter containing:
tensor([0.8300], requires_grad=True)


In [72]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

optimizer = torch.optim.SGD(
    multi_model.parameters(),
    lr=0.01
)

print("Weight:", multi_model.weight)
print("Bias:", multi_model.bias)

Weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Bias: Parameter containing:
tensor([0.8300], requires_grad=True)


In [73]:
print("Current weight:", multi_model.weight)
print("Current bias:", multi_model.bias)

print("Weight gradient:", multi_model.weight.grad)
print("Bias gradient:", multi_model.bias.grad)

Current weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Current bias: Parameter containing:
tensor([0.8300], requires_grad=True)
Weight gradient: None
Bias gradient: None


In [74]:
optimizer.step()

print("Updated weight:", multi_model.weight)
print("Updated bias:", multi_model.bias)

Updated weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Updated bias: Parameter containing:
tensor([0.8300], requires_grad=True)


In [ ]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

mse_loss = nn.MSELoss()

optimizer = torch.optim.SGD(
    multi_model.parameters(),
    lr=0.01
)

print("Starting weight:", multi_model.weight)
print("Starting bias:", multi_model.bias)

In [77]:
for epoch in range(10):
    optimizer.zero_grad()
    predictions = multi_model(inputs)
    loss = mse_loss(predictions, targets)
    loss.backward()
    optimizer.step()

    

Epoch 1 | Loss: 117.6551 | Weight: 1.3584 | Bias: 1.0252
Epoch 2 | Loss: 81.8460 | Weight: 1.8533 | Bias: 1.1868
Epoch 3 | Loss: 56.9976 | Weight: 2.2660 | Bias: 1.3204
Epoch 4 | Loss: 39.7546 | Weight: 2.6101 | Bias: 1.4306
Epoch 5 | Loss: 27.7888 | Weight: 2.8970 | Bias: 1.5215
Epoch 6 | Loss: 19.4847 | Weight: 3.1364 | Bias: 1.5962
Epoch 7 | Loss: 13.7215 | Weight: 3.3361 | Bias: 1.6575
Epoch 8 | Loss: 9.7214 | Weight: 3.5028 | Bias: 1.7075
Epoch 9 | Loss: 6.9445 | Weight: 3.6420 | Bias: 1.7483
Epoch 10 | Loss: 5.0166 | Weight: 3.7583 | Bias: 1.7812


In [89]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

mse_loss = nn.MSELoss()

optimizer = torch.optim.SGD(
    multi_model.parameters(),
    lr=0.01
)                                       #reset first step


print("Weight:", multi_model.weight)
print("Bias:", multi_model.bias)

Weight: Parameter containing:
tensor([[0.7645]], requires_grad=True)
Bias: Parameter containing:
tensor([0.8300], requires_grad=True)


In [88]:
for epoch in range(100):
    optimizer.zero_grad()
    predictions = multi_model(inputs) 
    loss = mse_loss(predictions, targets)
    loss.backward()
    optimizer.step()

    print(
        f"Epoch {epoch + 1} | "
        f"Loss: {loss.item():.4f} | "
        f"Weight: {multi_model.weight.item():.4f} | "
        f"Bias: {multi_model.bias.item():.4f}"
    )

Epoch 1 | Loss: 27.7888 | Weight: 2.8970 | Bias: 1.5215
Epoch 2 | Loss: 19.4847 | Weight: 3.1364 | Bias: 1.5962
Epoch 3 | Loss: 13.7215 | Weight: 3.3361 | Bias: 1.6575
Epoch 4 | Loss: 9.7214 | Weight: 3.5028 | Bias: 1.7075
Epoch 5 | Loss: 6.9445 | Weight: 3.6420 | Bias: 1.7483
Epoch 6 | Loss: 5.0166 | Weight: 3.7583 | Bias: 1.7812
Epoch 7 | Loss: 3.6776 | Weight: 3.8555 | Bias: 1.8076
Epoch 8 | Loss: 2.7473 | Weight: 3.9368 | Bias: 1.8287
Epoch 9 | Loss: 2.1007 | Weight: 4.0048 | Bias: 1.8453
Epoch 10 | Loss: 1.6508 | Weight: 4.0619 | Bias: 1.8582
Epoch 11 | Loss: 1.3375 | Weight: 4.1097 | Bias: 1.8679
Epoch 12 | Loss: 1.1190 | Weight: 4.1498 | Bias: 1.8751
Epoch 13 | Loss: 0.9662 | Weight: 4.1836 | Bias: 1.8801
Epoch 14 | Loss: 0.8590 | Weight: 4.2121 | Bias: 1.8833
Epoch 15 | Loss: 0.7836 | Weight: 4.2361 | Bias: 1.8850
Epoch 16 | Loss: 0.7301 | Weight: 4.2564 | Bias: 1.8855
Epoch 17 | Loss: 0.6918 | Weight: 4.2737 | Bias: 1.8850
Epoch 18 | Loss: 0.6642 | Weight: 4.2884 | Bias: 1.883

In [91]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets)

print("Number of samples:", len(dataset))

Number of samples: 4


In [92]:
print(dataset[0])

(tensor([1.]), tensor([5.]))


In [95]:
sample_input, sample_target = dataset[0]

print("Input:", sample_input)
print("Target:", sample_target)

Input: tensor([1.])
Target: tensor([5.])


In [96]:
from torch.utils.data import DataLoader

In [97]:
dataloader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=False
)

print("Number of batches:", len(dataloader))

Number of batches: 2


In [98]:
for batch_inputs, batch_targets in dataloader:
    print("Batch inputs:")
    print(batch_inputs)

    print("Batch targets:")
    print(batch_targets)

    print("Input shape:", batch_inputs.shape)
    print("Target shape:", batch_targets.shape)
    print()

Batch inputs:
tensor([[1.],
        [2.]])
Batch targets:
tensor([[ 5.],
        [10.]])
Input shape: torch.Size([2, 1])
Target shape: torch.Size([2, 1])

Batch inputs:
tensor([[3.],
        [4.]])
Batch targets:
tensor([[15.],
        [20.]])
Input shape: torch.Size([2, 1])
Target shape: torch.Size([2, 1])



In [110]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

mse_loss = nn.MSELoss()

optimizer = torch.optim.SGD(
    multi_model.parameters(),
    lr=0.01
)

In [111]:
for epoch in range(100):
    for batch_inputs, batch_targets in dataloader:
        optimizer.zero_grad()
        prediction = multi_model(batch_inputs)
        loss = mse_loss(prediction, batch_targets)
        loss.backward()
        optimizer.step()
    

In [112]:
print("Final weight:", multi_model.weight.item())
print("Final bias:", multi_model.bias.item())
print("Final batch loss:", loss.item())

Final weight: 4.640343189239502
Final bias: 1.102232575416565
Final batch loss: 0.08482860028743744


In [113]:
torch.manual_seed(42)

multi_model = nn.Linear(
    in_features=1,
    out_features=1
)

mse_loss = nn.MSELoss()

optimizer = torch.optim.SGD(
    multi_model.parameters(),
    lr=0.01
)

In [114]:
for epoch in range(100):
    epoch_loss = 0.0
    
    for batch_inputs, batch_targets in dataloader:
        optimizer.zero_grad()
        prediction = multi_model(batch_inputs)
        loss = mse_loss(prediction, batch_targets)
        epoch_loss += loss.item()
        loss.backward()
        optimizer.step()
    average_loss = epoch_loss / len(dataloader)

In [119]:
    print("Epoch:", epoch + 1, "Average Loss:", average_loss)

Epoch: 100 Average Loss: 0.21911277621984482
