In [2]:
import torch

print(torch.__version__)

2.14.0+cu130


In [3]:
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)   #scaler 0-dimension
print(scalar.shape)       
print(scalar.dtype)

0
torch.Size([])
torch.int64


In [5]:
vector = torch.tensor([7, 7])

print(vector)
print(vector.ndim)      #vector 1-dimension
print(vector.shape)
print(vector.dtype)

tensor([7, 7])
1
torch.Size([2])
torch.int64


In [6]:
matrix = torch.tensor([
    [7, 8],
    [9, 10]
])

print(matrix.ndim)   #matrix 2-dimension
print(matrix.shape)     
print(matrix.dtype)

2
torch.Size([2, 2])
torch.int64


In [7]:
print(matrix[0, 0])
print(matrix[0, 1])       # matrix -indexing
print(matrix[1, 0])
print(matrix[1, 1])

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [8]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],                 # 3-dimensional tensor
        [10, 11, 12]
    ]
])

print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [9]:
print(tensor_3d[0, 0, 0])
print(tensor_3d[0, 1, 2]) #indexing
print(tensor_3d[1, 0, 2])
print(tensor_3d[1, 1, 1])

tensor(1)
tensor(6)
tensor(9)
tensor(11)


In [10]:
print(tensor_3d[1])
print(tensor_3d[1][0])
print(tensor_3d[1][0][2])

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([7, 8, 9])
tensor(9)


In [11]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print(float_tensor)
print(float_tensor.dtype)
print(float_tensor.shape)
print(float_tensor.ndim)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
1


In [12]:
float_64_tensor = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=torch.float64
)

print(float_64_tensor)
print(float_64_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


In [13]:
vector_float = vector.to(dtype=torch.float32)

print(vector)
print(vector.dtype)

print(vector_float)
print(vector_float.dtype)

tensor([7, 7])
torch.int64
tensor([7., 7.])
torch.float32


In [14]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [15]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

elementwise_result = tensor_a * tensor_b       # element-wise multiplication


print(elementwise_result)

tensor([ 4, 10, 18])


In [16]:
matrix_result = torch.matmul(tensor_a, tensor_b)  # matrix-multiplication

print(matrix_result)

tensor(32)


In [17]:
matrix_a = torch.tensor([
    [1, 2],
    [3, 4]
])
                 # matrix multiplication with 2D matrices
                        
matrix_b = torch.tensor([
    [5, 6],
    [7, 8]
])

result = torch.matmul(matrix_a, matrix_b)

print(result)

tensor([[19, 22],
        [43, 50]])


In [18]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a.shape)
print(b.shape)

result = torch.matmul(a, b)

print(result)
print(result.shape)

torch.Size([2, 3])
torch.Size([3, 4])
tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128]])
torch.Size([2, 4])


In [19]:
print(a)

print(a.T)

print(a.shape)
print(a.T.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])


In [20]:
inputs = torch.tensor([2.0, 3.0, 4.0])

weights = torch.tensor([0.5, 0.2, 0.1])

bias = torch.tensor(0.5)

output = torch.matmul(inputs, weights) + bias

print(output)

tensor(2.5000)


In [21]:
import torch.nn as nn #import neural network

In [22]:
linear_layer = nn.Linear(
    in_features=3,
    out_features=1
)

print(linear_layer)

Linear(in_features=3, out_features=1, bias=True)


In [23]:
print(linear_layer.weight)
print(linear_layer.bias)

print(linear_layer.weight.shape)
print(linear_layer.bias.shape)

Parameter containing:
tensor([[ 0.2493, -0.0301, -0.2993]], requires_grad=True)
Parameter containing:
tensor([-0.4811], requires_grad=True)
torch.Size([1, 3])
torch.Size([1])


In [24]:
inputs = torch.tensor([2.0, 3.0, 4.0])

output = linear_layer(inputs)

print(output)

tensor([-1.2702], grad_fn=<ViewBackward0>)


In [25]:
print(output.requires_grad)
print(output.grad_fn)

True


In [26]:
print(inputs.requires_grad)
print(linear_layer.weight.requires_grad)
print(linear_layer.bias.requires_grad)
print(output.requires_grad)
print(output.grad_fn)

False
True
True
True


In [27]:
x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [28]:
y.backward()

print(x.grad)

tensor(6.)


In [29]:
x1 = 3.0
x2 = 3.001

y1 = x1 ** 2
y2 = x2 ** 2

change_in_x = x2 - x1
change_in_y = y2 - y1

estimated_gradient = change_in_y / change_in_x

print(change_in_x)
print(change_in_y)
print(estimated_gradient)

0.0009999999999998899
0.006000999999999479
6.00100000000014


In [30]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)


In [31]:
loss.backward()

print(weight.grad)

tensor(-32.)


In [32]:
learning_rate = 0.1

with torch.no_grad():
    weight -= learning_rate * weight.grad
    
print("Updated weight:", weight)

Updated weight: tensor(4.2000, requires_grad=True)


In [33]:
prediction = weight * input_value 

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(8.4000, grad_fn=<MulBackward0>)
Loss: tensor(2.5600, grad_fn=<PowBackward0>)


In [34]:
weight.grad.zero_()

 # reset gradient

print(weight.grad)

tensor(0.)


In [35]:
loss.backward()

print(weight.grad)

tensor(-6.4000)


In [53]:
with torch.no_grad():
    weight -= learning_rate * weight.grad # update new weight = old weight−(learning rate×gradient)


print("Updated weight:", weight)

Updated weight: tensor(4.9987, requires_grad=True)


In [37]:
prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(9.6800, grad_fn=<MulBackward0>)
Loss: tensor(0.1024, grad_fn=<PowBackward0>)


In [46]:
for epoch in range(5):
    print("Epoch", epoch + 1) # 1-5
    

Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5


In [49]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

for epoch in range(5):
    prediction = weight * input_value

    loss =  (prediction - target) ** 2

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction)
    print("Loss:", loss)

Epoch: 1
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 2
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 3
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 4
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)
Epoch: 5
Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)


In [50]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

prediction = weight * input_value

loss =  (prediction - target) ** 2

loss.backward()

print("Prediction", prediction)
print("Loss", loss)
print("Gradient", weight.grad)

Prediction tensor(2., grad_fn=<MulBackward0>)
Loss tensor(64., grad_fn=<PowBackward0>)
Gradient tensor(-32.)


In [51]:
weight.grad.zero_()

print("Gradient after reset:", weight.grad)

Gradient after reset: tensor(0.)


In [52]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

learning_rate = 0.1

for epoch in range(5):

    prediction = weight * input_value      #1×2=2

    loss = (prediction - target) ** 2      # (2 - 10) raise to power 2

    loss.backward() # backpropagation

    with torch.no_grad():
        weight -= learning_rate * weight.grad   # weight=1−(0.1×−32)

    weight.grad.zero_()

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction.item())
    print("Loss:", loss.item())
    print("Weight:", weight.item())
    print()

Epoch: 1
Prediction: 2.0
Loss: 64.0
Weight: 4.199999809265137

Epoch: 2
Prediction: 8.399999618530273
Loss: 2.5600011348724365
Weight: 4.840000152587891

Epoch: 3
Prediction: 9.680000305175781
Loss: 0.1023998036980629
Weight: 4.9679999351501465

Epoch: 4
Prediction: 9.935999870300293
Loss: 0.004096016753464937
Weight: 4.993599891662598

Epoch: 5
Prediction: 9.987199783325195
Loss: 0.00016384554328396916
Weight: 4.998720169067383



In [59]:
weight = torch.tensor(1.0, requires_grad=True)

optimizer = torch.optim.SGD(
    [weight],
    lr=0.1
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [60]:
input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

prediction = weight * input_value
loss = (prediction - target) ** 2

loss.backward()

print("Weight before optimizer:", weight.item())
print("Gradient:", weight.grad.item())

Weight before optimizer: 1.0
Gradient: -32.0


In [61]:
optimizer.step()

print("Weight after optimizer:", weight.item())

Weight after optimizer: 4.199999809265137


In [62]:
print("Gradient before zero_grad:", weight.grad)

optimizer.zero_grad()

print("Gradient after zero_grad:", weight.grad)

Gradient before zero_grad: tensor(-32.)
Gradient after zero_grad: None


In [63]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)
target = torch.tensor(10.0)

optimizer = torch.optim.SGD([weight], lr=0.1)

for epoch in range(5):

    optimizer.zero_grad()

    prediction = weight * input_value

    loss = (prediction - target) ** 2

    loss.backward()

    optimizer.step()

    print("Epoch:", epoch + 1)
    print("Prediction:", prediction.item())
    print("Loss:", loss.item())
    print("Weight:", weight.item())
    print()

Epoch: 1
Prediction: 2.0
Loss: 64.0
Weight: 4.199999809265137

Epoch: 2
Prediction: 8.399999618530273
Loss: 2.5600011348724365
Weight: 4.840000152587891

Epoch: 3
Prediction: 9.680000305175781
Loss: 0.1023998036980629
Weight: 4.9679999351501465

Epoch: 4
Prediction: 9.935999870300293
Loss: 0.004096016753464937
Weight: 4.993599891662598

Epoch: 5
Prediction: 9.987199783325195
Loss: 0.00016384554328396916
Weight: 4.998720169067383



In [64]:
linear_model = nn.Linear(
    in_features=1,
    out_features=1
)

print(linear_model)

print("Weight:", linear_model.weight)
print("Bias:", linear_model.bias)

print("Weight shape:", linear_model.weight.shape)
print("Bias shape:", linear_model.bias.shape)

Linear(in_features=1, out_features=1, bias=True)
Weight: Parameter containing:
tensor([[-0.2111]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.0013], requires_grad=True)
Weight shape: torch.Size([1, 1])
Bias shape: torch.Size([1])


In [65]:
input_value = torch.tensor([[2.0]])

prediction = linear_model(input_value)

print("Input shape:", input_value.shape)
print("Prediction:", prediction)
print("Prediction shape:", prediction.shape)

Input shape: torch.Size([1, 1])
Prediction: tensor([[-0.4235]], grad_fn=<AddmmBackward0>)
Prediction shape: torch.Size([1, 1])


In [66]:
target = torch.tensor([[10.0]])

loss = (prediction - target) ** 2

print("Prediction", prediction)
print("Loss", loss)
print("Target", target)

Prediction tensor([[-0.4235]], grad_fn=<AddmmBackward0>)
Loss tensor([[108.6485]], grad_fn=<PowBackward0>)
Target tensor([[10.]])


In [67]:
loss.backward()

print("Weight gradient:", linear_model.weight.grad)
print("Bias gradient:", linear_model.bias.grad)

Weight gradient: tensor([[-41.6938]])
Bias gradient: tensor([-20.8469])


In [68]:
optimizer = torch.optim.SGD(
    linear_model.parameters(),
    lr=0.01
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [69]:
optimizer.step()

print("Updated weight:", linear_model.weight)
print("Updated bias:", linear_model.bias)

Updated weight: Parameter containing:
tensor([[0.2059]], requires_grad=True)
Updated bias: Parameter containing:
tensor([0.2072], requires_grad=True)


In [70]:
new_prediction = linear_model(input_value)
new_loss = (new_prediction - target) ** 2

print("Old prediction:", prediction)
print("New prediction:", new_prediction)
print("Old loss:", loss)
print("New loss:", new_loss)

Old prediction: tensor([[-0.4235]], grad_fn=<AddmmBackward0>)
New prediction: tensor([[0.6189]], grad_fn=<AddmmBackward0>)
Old loss: tensor([[108.6485]], grad_fn=<PowBackward0>)
New loss: tensor([[88.0053]], grad_fn=<PowBackward0>)


In [71]:
print("Weight gradient still stored:", linear_model.weight.grad)
print("Bias gradient still stored:", linear_model.bias.grad)

Weight gradient still stored: tensor([[-41.6938]])
Bias gradient still stored: tensor([-20.8469])


In [72]:
optimizer.zero_grad()

print("Weight gradient after zero_grad:", linear_model.weight.grad)
print("Bias gradient after zero_grad:", linear_model.bias.grad)

Weight gradient after zero_grad: None
Bias gradient after zero_grad: None


In [73]:
new_loss.backward()

print("New weight gradient:", linear_model.weight.grad)
print("New bias gradient:", linear_model.bias.grad)

New weight gradient: tensor([[-37.5245]])
New bias gradient: tensor([-18.7622])
