In [1]:
import torch

print(torch.__version__)

2.14.0+cu130


In [2]:
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [3]:
print(scalar.ndim)   #scaler 0-dimension
print(scalar.shape)       
print(scalar.dtype)

0
torch.Size([])
torch.int64


In [4]:
vector = torch.tensor([7, 7])

print(vector)
print(vector.ndim)      #vector 1-dimension
print(vector.shape)
print(vector.dtype)

tensor([7, 7])
1
torch.Size([2])
torch.int64


In [5]:
matrix = torch.tensor([
    [7, 8],
    [9, 10]
])

print(matrix.ndim)   #matrix 2-dimension
print(matrix.shape)     
print(matrix.dtype)

2
torch.Size([2, 2])
torch.int64


In [6]:
print(matrix[0, 0])
print(matrix[0, 1])       # matrix -indexing
print(matrix[1, 0])
print(matrix[1, 1])

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [7]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],                 # 3-dimensional tensor
        [10, 11, 12]
    ]
])

print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [8]:
print(tensor_3d[0, 0, 0])
print(tensor_3d[0, 1, 2]) #indexing
print(tensor_3d[1, 0, 2])
print(tensor_3d[1, 1, 1])

tensor(1)
tensor(6)
tensor(9)
tensor(11)


In [9]:
print(tensor_3d[1])
print(tensor_3d[1][0])
print(tensor_3d[1][0][2])

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([7, 8, 9])
tensor(9)


In [10]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print(float_tensor)
print(float_tensor.dtype)
print(float_tensor.shape)
print(float_tensor.ndim)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
1


In [11]:
float_64_tensor = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=torch.float64
)

print(float_64_tensor)
print(float_64_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


In [12]:
vector_float = vector.to(dtype=torch.float32)

print(vector)
print(vector.dtype)

print(vector_float)
print(vector_float.dtype)

tensor([7, 7])
torch.int64
tensor([7., 7.])
torch.float32


In [13]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [14]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

elementwise_result = tensor_a * tensor_b       # element-wise multiplication


print(elementwise_result)

tensor([ 4, 10, 18])


In [15]:
matrix_result = torch.matmul(tensor_a, tensor_b)  # matrix-multiplication

print(matrix_result)

tensor(32)


In [16]:
matrix_a = torch.tensor([
    [1, 2],
    [3, 4]
])
                 # matrix multiplication with 2D matrices
                        
matrix_b = torch.tensor([
    [5, 6],
    [7, 8]
])

result = torch.matmul(matrix_a, matrix_b)

print(result)

tensor([[19, 22],
        [43, 50]])


In [17]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a.shape)
print(b.shape)

result = torch.matmul(a, b)

print(result)
print(result.shape)

torch.Size([2, 3])
torch.Size([3, 4])
tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128]])
torch.Size([2, 4])


In [18]:
print(a)

print(a.T)

print(a.shape)
print(a.T.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])


In [19]:
inputs = torch.tensor([2.0, 3.0, 4.0])

weights = torch.tensor([0.5, 0.2, 0.1])

bias = torch.tensor(0.5)

output = torch.matmul(inputs, weights) + bias

print(output)

tensor(2.5000)


In [20]:
import torch.nn as nn #import neural network

In [21]:
linear_layer = nn.Linear(
    in_features=3,
    out_features=1
)

print(linear_layer)

Linear(in_features=3, out_features=1, bias=True)


In [22]:
print(linear_layer.weight)
print(linear_layer.bias)

print(linear_layer.weight.shape)
print(linear_layer.bias.shape)

Parameter containing:
tensor([[-0.4339,  0.5174,  0.5213]], requires_grad=True)
Parameter containing:
tensor([0.0673], requires_grad=True)
torch.Size([1, 3])
torch.Size([1])


In [23]:
inputs = torch.tensor([2.0, 3.0, 4.0])

output = linear_layer(inputs)

print(output)

tensor([2.8371], grad_fn=<ViewBackward0>)


In [24]:
print(output.requires_grad)
print(output.grad_fn)

True


In [25]:
print(inputs.requires_grad)
print(linear_layer.weight.requires_grad)
print(linear_layer.bias.requires_grad)
print(output.requires_grad)
print(output.grad_fn)

False
True
True
True


In [26]:
x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [27]:
y.backward()

print(x.grad)

tensor(6.)


In [28]:
x1 = 3.0
x2 = 3.001

y1 = x1 ** 2
y2 = x2 ** 2

change_in_x = x2 - x1
change_in_y = y2 - y1

estimated_gradient = change_in_y / change_in_x

print(change_in_x)
print(change_in_y)
print(estimated_gradient)

0.0009999999999998899
0.006000999999999479
6.00100000000014


In [29]:
weight = torch.tensor(1.0, requires_grad=True)

input_value = torch.tensor(2.0)

target = torch.tensor(10.0)

prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(2., grad_fn=<MulBackward0>)
Loss: tensor(64., grad_fn=<PowBackward0>)


In [30]:
loss.backward()

print(weight.grad)

tensor(-32.)


In [33]:
learning_rate = 0.1

with torch.no_grad():
    weight -= learning_rate * weight.grad
    
print("Updated weight:", weight)

Updated weight: tensor(4.2000, requires_grad=True)


In [35]:
prediction = weight * input_value 

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(8.4000, grad_fn=<MulBackward0>)
Loss: tensor(2.5600, grad_fn=<PowBackward0>)


In [37]:
weight.grad.zero_()

 # reset gradient

print(weight.grad)

tensor(0.)


In [38]:
loss.backward()

print(weight.grad)

tensor(-6.4000)


In [39]:
with torch.no_grad():
    weight -= learning_rate * weight.grad # update new weight 

print("Updated weight:", weight)

Updated weight: tensor(4.8400, requires_grad=True)


In [41]:
prediction = weight * input_value

loss = (prediction - target) ** 2

print("Prediction:", prediction)
print("Loss:", loss)


Prediction: tensor(9.6800, grad_fn=<MulBackward0>)
Loss: tensor(0.1024, grad_fn=<PowBackward0>)
